/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import HomeImage from 'src/assets/images/QuestAItestingcomponent_HOME.png';
import { styled } from '@mui/material/styles';
import RenderizávelUi from 'src/components/RenderizávelUi/RenderizávelUi';
import Cards from 'src/components/Cards/Cards';

const QuestAiTestingCompon = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `2726px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const Home = styled('img')({
  height: `1975px`,
  width: `428px`,
  position: `absolute`,
  left: `471px`,
  top: `0px`,
});

const RenderizávelUi1 = styled(RenderizávelUi)(({ theme }) => ({
  width: `428px`,
  height: `2726px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const Cards1 = styled(Cards)(({ theme }) => ({
  position: `absolute`,
  left: `487px`,
  top: `2031px`,
}));

function QuestAiTestingComponent(props) {
  return (
    <QuestAiTestingCompon className={props.className}>
      <Home src={HomeImage} loading="lazy" alt={'HOME'} />
      <RenderizávelUi1 />
      <Cards1 />
    </QuestAiTestingCompon>
  );
}

export default QuestAiTestingComponent;
