/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import VectorImage from 'src/assets/images/HOME_Vector.png';
import LogoImage from 'src/assets/images/HOME_Logo.png';
import Vector1Image from 'src/assets/images/HOME_Vector_1.png';
import { styled } from '@mui/material/styles';
import Title from 'src/components/Title/Title';
import HomeCta from 'src/components/HomeCta/HomeCta';
import Pills from 'src/components/Pills/Pills';
import Cards from 'src/components/Cards/Cards';

const Home1 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
  height: 'auto',
  width: 'fit-content',
});

const IconHamburgerMenu = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `25px`,
  width: `35px`,
  margin: `0px`,
});

const Vector = styled('img')({
  height: `25px`,
  width: `35px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Logo = styled('img')({
  height: `40px`,
  width: `147.5px`,
  objectFit: `cover`,
  margin: `0px`,
});

const Vector1 = styled('img')({
  height: `44px`,
  width: `46px`,
  margin: `0px`,
});

const HomeHero = styled('div')({
  backgroundColor: `rgba(73, 94, 87, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px 16px 40px 16px`,
  boxSizing: `border-box`,
  width: `428px`,
  margin: `0px`,
});

const Title1 = styled(Title)(({ theme }) => ({
  margin: `0px`,
}));

const HomeCta1 = styled(HomeCta)(({ theme }) => ({
  margin: `16px 0px 0px 0px`,
}));

const HomeHero1 = styled('div')({
  backgroundColor: `rgba(73, 94, 87, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px 16px 40px 16px`,
  boxSizing: `border-box`,
  width: `428px`,
  margin: `0px`,
});

const Title2 = styled(Title)(({ theme }) => ({
  margin: `0px`,
}));

const HomeCta2 = styled(HomeCta)(({ theme }) => ({
  margin: `16px 0px 0px 0px`,
}));

const HomeHero2 = styled('div')({
  backgroundColor: `rgba(73, 94, 87, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px 16px 40px 16px`,
  boxSizing: `border-box`,
  width: `428px`,
  margin: `0px`,
});

const Title3 = styled(Title)(({ theme }) => ({
  margin: `0px`,
}));

const HomeCta3 = styled(HomeCta)(({ theme }) => ({
  margin: `16px 0px 0px 0px`,
}));

const Rectangle2 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  height: `130px`,
  width: `430px`,
  margin: `0px`,
});

const HomeOrder = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  border: `1px solid rgba(51, 51, 51, 0.25)`,
  boxSizing: `border-box`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `40px 0px 32px 0px`,
  width: `396px`,
  margin: `0px`,
});

const OrderForDelivery = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Karla`,
  fontWeight: `800`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `uppercase`,
  width: `296px`,
  margin: `0px`,
});

const Pills1 = styled(Pills)(({ theme }) => ({
  width: `412px`,
  margin: `16px 0px 0px 0px`,
}));

const Frame4 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `675px`,
  width: `396px`,
  margin: `0px`,
});

const Cards1 = styled(Cards)(({ theme }) => ({
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

function Home(props) {
  return (
    <Home1>
      <IconHamburgerMenu>
        <Vector src={VectorImage} loading="lazy" alt={'Vector'} />
      </IconHamburgerMenu>
      <Logo src={LogoImage} loading="lazy" alt={'Logo'} />
      <Vector1 src={Vector1Image} loading="lazy" alt={'Vector'} />
      <HomeHero>
        <Title1 />
        <HomeCta1 />
      </HomeHero>
      <HomeHero1>
        <Title2 />
        <HomeCta2 />
      </HomeHero1>
      <HomeHero2>
        <Title3 />
        <HomeCta3 />
      </HomeHero2>
      {false && <Rectangle2></Rectangle2>}
      <HomeOrder>
        <OrderForDelivery>{`Order FOR DELIVERY!`}</OrderForDelivery>
        <Pills1 />
      </HomeOrder>
      <Frame4>
        <Cards1 />
      </Frame4>
    </Home1>
  );
}

export default Home;
